// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/autherain/test/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersReadWriter creates a new instance of MockUsersReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersReadWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersReadWriter {
	mock := &MockUsersReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersReadWriter is an autogenerated mock type for the UsersReadWriter type
type MockUsersReadWriter struct {
	mock.Mock
}

type MockUsersReadWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersReadWriter) EXPECT() *MockUsersReadWriter_Expecter {
	return &MockUsersReadWriter_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersReadWriter
func (_mock *MockUsersReadWriter) CreateUser(user1 *user.User) error {
	ret := _mock.Called(user1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*user.User) error); ok {
		r0 = returnFunc(user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersReadWriter_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersReadWriter_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user1 *user.User
func (_e *MockUsersReadWriter_Expecter) CreateUser(user1 interface{}) *MockUsersReadWriter_CreateUser_Call {
	return &MockUsersReadWriter_CreateUser_Call{Call: _e.mock.On("CreateUser", user1)}
}

func (_c *MockUsersReadWriter_CreateUser_Call) Run(run func(user1 *user.User)) *MockUsersReadWriter_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.User
		if args[0] != nil {
			arg0 = args[0].(*user.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersReadWriter_CreateUser_Call) Return(err error) *MockUsersReadWriter_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersReadWriter_CreateUser_Call) RunAndReturn(run func(user1 *user.User) error) *MockUsersReadWriter_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersReadWriter
func (_mock *MockUsersReadWriter) DeleteUser(selector *user.UserSelector) error {
	ret := _mock.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*user.UserSelector) error); ok {
		r0 = returnFunc(selector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersReadWriter_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersReadWriter_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - selector *user.UserSelector
func (_e *MockUsersReadWriter_Expecter) DeleteUser(selector interface{}) *MockUsersReadWriter_DeleteUser_Call {
	return &MockUsersReadWriter_DeleteUser_Call{Call: _e.mock.On("DeleteUser", selector)}
}

func (_c *MockUsersReadWriter_DeleteUser_Call) Run(run func(selector *user.UserSelector)) *MockUsersReadWriter_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.UserSelector
		if args[0] != nil {
			arg0 = args[0].(*user.UserSelector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersReadWriter_DeleteUser_Call) Return(err error) *MockUsersReadWriter_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersReadWriter_DeleteUser_Call) RunAndReturn(run func(selector *user.UserSelector) error) *MockUsersReadWriter_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUser provides a mock function for the type MockUsersReadWriter
func (_mock *MockUsersReadWriter) ReadUser(selector *user.UserSelector) (*user.User, bool, error) {
	ret := _mock.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for ReadUser")
	}

	var r0 *user.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*user.UserSelector) (*user.User, bool, error)); ok {
		return returnFunc(selector)
	}
	if returnFunc, ok := ret.Get(0).(func(*user.UserSelector) *user.User); ok {
		r0 = returnFunc(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*user.UserSelector) bool); ok {
		r1 = returnFunc(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(*user.UserSelector) error); ok {
		r2 = returnFunc(selector)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersReadWriter_ReadUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUser'
type MockUsersReadWriter_ReadUser_Call struct {
	*mock.Call
}

// ReadUser is a helper method to define mock.On call
//   - selector *user.UserSelector
func (_e *MockUsersReadWriter_Expecter) ReadUser(selector interface{}) *MockUsersReadWriter_ReadUser_Call {
	return &MockUsersReadWriter_ReadUser_Call{Call: _e.mock.On("ReadUser", selector)}
}

func (_c *MockUsersReadWriter_ReadUser_Call) Run(run func(selector *user.UserSelector)) *MockUsersReadWriter_ReadUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.UserSelector
		if args[0] != nil {
			arg0 = args[0].(*user.UserSelector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersReadWriter_ReadUser_Call) Return(user1 *user.User, b bool, err error) *MockUsersReadWriter_ReadUser_Call {
	_c.Call.Return(user1, b, err)
	return _c
}

func (_c *MockUsersReadWriter_ReadUser_Call) RunAndReturn(run func(selector *user.UserSelector) (*user.User, bool, error)) *MockUsersReadWriter_ReadUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUserByEmail provides a mock function for the type MockUsersReadWriter
func (_mock *MockUsersReadWriter) ReadUserByEmail(email string) (*user.User, bool, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ReadUserByEmail")
	}

	var r0 *user.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*user.User, bool, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersReadWriter_ReadUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUserByEmail'
type MockUsersReadWriter_ReadUserByEmail_Call struct {
	*mock.Call
}

// ReadUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUsersReadWriter_Expecter) ReadUserByEmail(email interface{}) *MockUsersReadWriter_ReadUserByEmail_Call {
	return &MockUsersReadWriter_ReadUserByEmail_Call{Call: _e.mock.On("ReadUserByEmail", email)}
}

func (_c *MockUsersReadWriter_ReadUserByEmail_Call) Run(run func(email string)) *MockUsersReadWriter_ReadUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersReadWriter_ReadUserByEmail_Call) Return(user1 *user.User, b bool, err error) *MockUsersReadWriter_ReadUserByEmail_Call {
	_c.Call.Return(user1, b, err)
	return _c
}

func (_c *MockUsersReadWriter_ReadUserByEmail_Call) RunAndReturn(run func(email string) (*user.User, bool, error)) *MockUsersReadWriter_ReadUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsersReadWriter
func (_mock *MockUsersReadWriter) UpdateUser(user1 *user.User) error {
	ret := _mock.Called(user1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*user.User) error); ok {
		r0 = returnFunc(user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersReadWriter_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersReadWriter_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user1 *user.User
func (_e *MockUsersReadWriter_Expecter) UpdateUser(user1 interface{}) *MockUsersReadWriter_UpdateUser_Call {
	return &MockUsersReadWriter_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user1)}
}

func (_c *MockUsersReadWriter_UpdateUser_Call) Run(run func(user1 *user.User)) *MockUsersReadWriter_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.User
		if args[0] != nil {
			arg0 = args[0].(*user.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersReadWriter_UpdateUser_Call) Return(err error) *MockUsersReadWriter_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersReadWriter_UpdateUser_Call) RunAndReturn(run func(user1 *user.User) error) *MockUsersReadWriter_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
